### ISSUE TITLE
About the StylePatchNCE loss code?

### ISSUE THREAD

**Issue by zhangquanwei962** [Yuxinn-J/Scenimefy#2]
Hi, thank you for your greate work! But I don't find where the StylePatchNCE loss, can you help me? I'm looking forward your repying.

**Comment by Yuxinn-J** [comment]
Hiii, thanks for being interested! I'm working on tidying up the training code, so the StylePatchNCE loss isn't there just yet. Thanks for your patience and please stay tuned :-)

**Comment by zhangquanwei962** [comment]
> Hiii, thanks for being interested! I'm working on tidying up the training code, so the StylePatchNCE loss isn't there just yet. Thanks for your patience and please stay tuned :-)

Sure, thanks for your timely reply.  Looking forward to future updates. Have a good day!

**Comment by Yuxinn-J** [comment]
The train code with StylePatchNCE loss is now released. Thank you for waiting!
