### ISSUE TITLE
Model training

### ISSUE THREAD

**Issue by Dmitrii-Demenko** [Yuxinn-J/Scenimefy#5]
Could you please tell me how to train your model for this code?

**Comment by Yuxinn-J** [comment]
Hiii, thanks for your attention! The training code isn't quite ready for release at this time. I will provide comprehensive guidance on how to train the model once the code is available. Thanks for the patience and please stay tuned :-)

**Comment by zhanghongyong123456** [comment]
> Hiii, thanks for your attention! The training code isn't quite ready for release at this time. I will provide comprehensive guidance on how to train the model once the code is available. Thanks for the patience and please stay tuned :-)

When will the training code be released?

**Comment by Yuxinn-J** [comment]
Hiii, I plan to release it in the upcoming week, ideally before the ICCV conference. I try to deliver it asap, but please bear with me as Im currently swamped with midterms.

**Comment by zhanghongyong123456** [comment]
> Hiii, I plan to release it in the upcoming week, ideally before the ICCV conference. I try to deliver it asap, but please bear with me as Im currently swamped with midterms.

ok,thanks

**Comment by zhanghongyong123456** [comment]
> Hiii, I plan to release it in the upcoming week, ideally before the ICCV conference. I try to deliver it asap, but please bear with me as Im currently swamped with midterms.

about   train  code,thanks you

**Comment by Yuxinn-J** [comment]
The training code is now available. I appreciate your understanding and patience.
